apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  namespace: netboot-pihole
  labels:
    app: pihole
    component: pihole
    tier: frontend
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  selector:
    app: pihole
    component: pihole
    tier: frontend
  ports:
  - name: web-interface
    protocol: TCP
    port: 80
    targetPort: 80
  - name: dns
    protocol: TCP
    port: 53
    targetPort: 53
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: #{service.ip}#
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  namespace: netboot-pihole
  labels:
    app: pihole
    component: pihole
    tier: frontend
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  selector:
    app: pihole
    component: pihole
    tier: frontend
  ports:
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: #{service.ip}#